# Generated by Django 3.2.12 on 2024-03-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supaswa1', '0002_rename_event_id_data_event_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Temperature_value',
            new_name='Temperature',
        ),
    ]
